name = "restaurant-app"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-03-20"

[assets]
directory = "./.svelte-kit/cloudflare"
binding = "ASSETS"

[build]
command = "npm run build"

# Bind your D1 database
[[d1_databases]]
binding = "DB" # This is how you'll access it in your code (event.platform.env.DB)
database_name = "tawa-kettles"
database_id = "796a1f1d-2eeb-49fa-9b89-e5851ae1f458" # Get this from your Cloudflare dashboard or `wrangler d1 list`
migrations_dir = "migrations"